# TAP SCHEDULER DEVICE CONFIGURATION
TAP_SCHEDULER_MAKE = 'Logitech'
TAP_SCHEDULER_MODEL = 'VR0028'
TAP_SCHEDULER_PROC = 'Snapdragon'
TAP_SCHEDULER_RAM = '8 GB'
TAP_SCHEDULER_OS = 'Android'
TAP_SCHEDULER_OSV  = '0.915.703'
TAP_SCHEDULER_SW  = '1.12.703'
